# Site settings
title: Articles
description: Independent analysis and commentary on political and economic systems
url: https://tropinalexey.github.io
baseurl: /articles

# Author settings
author:
  name: Alexey Tropin
  email: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:title/

# GitHub Pages safe plugins only
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:title/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor/
  - node_modules/
  - .github/
  - cleanup-demo.sh

# Include files
include:
  - _pages

# GitHub Pages settings
safe: true
incremental: false
